name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.3.0
  image_picker: ^1.2.3
  file_picker: ^11.0.2
  supabase_flutter: ^2.8.0
  flutter_local_notifications: ^22.1.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Конфигурация иконки приложения (Android, iOS, ПК)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
    
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  # Регистрация ассетов для иконки
  assets:
    - assets/icon/app_icon.png