name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  foundation:

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.3.0
  image_picker: ^1.2.3
  file_picker: ^11.0.2
  supabase_flutter: ^2.8.0
  flutter_local_notifications: ^22.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true